on:
  push:
    branches: [ "main", "feature/e2e_tests"]
  pull_request:
    branches: [ "main" ]

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses : gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew build --scan
      - uses: actions/up`load-artifact@v2
        with:
          name: build
          path: build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Unit tests
        run: ./gradlew test --scan

  e2e-test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Unit tests
        run: ./gradlew integrationTest



#    lint:
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v3
#        - name: Cancel Previous Redundant Builds
#            - uses: actions/checkout@v3
#          with:
#            access_token: ${{github.token}}





#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Setup Gradle
#        uses : gradle/gradle-build-action@v2
#      - name: Build app
#        run: ./gradlew assemble test --scan
